#!/usr/bin/python
import sys, time, os, subprocess

dimension = sys.argv[1] # pass in an integer to this script

jreal  = "./bin/jexe.ijs"
creal  = "./bin/cexe.out"

def timer(cmd):
    """ Measure the time it takes to invoke the given command
    using a shell subprocess. """
    start = end = 0
    start = time.time()
    myProcess = subprocess.Popen(cmd, shell=True)
    myProcess.wait()
    end = time.time()
    return end - start

def av(filename, iters = 5):
    avg = 0
    for i in range(iters):
        avg += timer(filename)
    return avg / iters

def columnBuilder(cmd):
    output = ""
    for i in range(int(dimension)):
        output += str(timer(cmd + " " + str(i))) + "\n"
    return output

f = open("output/coutput.csv",'w')
f.write(columnBuilder(creal))
f.close()
f = open("output/joutput.csv",'w')
f.write(columnBuilder(jreal))
f.close()

