// a c++ file to process the results of a data logging run of my oscilloscope.
// the scope saves its run as a bunch of csv files, to use this program, put the
// scope files in a directory "raw" and position this program so it can access raw/[files].
// that is, the top-level structure should look like this:
//
// some-dir/
//   this_program
//   raw/
//     file1
//     file2
//     ...
//     fileN

// includes
#include <fstream>
#include <vector>
#include <sstream>

// constants
const std::string inputNameList = "csvNames"; // the name of the file generated by the Python script
const std::string outputName = "processed/test1processed.txt"; // the name of the file this program makes
// might eventually make this a command-line param if the program is useful:
int n = 4; // the column number (0-indexed) to isolate

// functions
std::vector<std::string> csvFileVector(std::string fileName) {
  // get the names of the CSV files from a pre-generated text file
  std::vector<std::string> result;
  std::ifstream f;
  std::string line;
  // open the file and read the lines into a vector of strings
  f.open(fileName, std::ios::in);
  while(!getline(f, line).eof()) {
    result.push_back(line);
  }
  f.close();
  return result;
}

// found this here: http://stackoverflow.com/a/236803
std::vector<std::string> &split(const std::string &s, char delim, std::vector<std::string> &elems) {
    std::stringstream ss(s);
    std::string item;
    while (std::getline(ss, item, delim)) {
        elems.push_back(item);
    }
    return elems;
}

// write output to file
int main() {
  // open a stream for writing
  std::ofstream result;
  result.open(outputName, std::ios::out);

  // read the streams
  for(auto& csvFile : csvFileVector(inputNameList)){
    // std::cout << csvFile << std::endl; // prints 'test1.csv test2.csv' etc.
    std::string row;
    std::ifstream f;
    f.open(csvFile, std::ios::in);

    while(!std::getline(f, row).eof()) {
      std::vector<std::string> elms;
      // split the row
      split(row, ',', elms);
      // concat the nth column to the output file
      if (n > elms.size() - 1) {
        n = elms.size() - 1;
      }
      result << elms[n] << std::endl;
    }
    f.close();
  }
  // close the output stream
  result.close();
}
